### ISSUE TITLE
Brackets have wrong height

### ISSUE THREAD

**Issue by Integral** [substance/archivist-composer#46]
on initial loadpage
![](http://s27.postimg.org/yo66tum9f/Screen_Shot_2015_04_21_at_12_12_48.png)

disappearing after any operation

steps to reproduce:
- come and see in Daniel's laptop

**Comment by michael** [comment]
I don't see the wrong height problem anymore. However, if I delete a subject annotation by removing the wrapped content the brackets do not get updated:

The problem is that we only check for changes of `content.nodes`. 

```
  onDocumentChange: function(change) {
    // console.log('##### ContainerComponent.onDocumentChange', change);
    if (change.isAffected([this.props.node.id, 'nodes'])) {
      var self = this;
      // console.log('##### calling forceUpdate after document change');
      this.forceUpdate(function() {
        self.updateBrackets();
      });
    }
    // eagerly update brackets on every change
    else {
      this.updateBrackets();
    }
  }
```

How would I formalize the check for when a subject_annotation is being deleted?

**Comment by michael** [comment]
Fixed.
